SUPABASE_URL = "..."
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpra2tpcnBnZ3RjemJkenFxbHljIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2OTUwMDcwOCwiZXhwIjoyMDg1MDc2NzA4fQ.VaF2DdhuiYdbRnRQg9rbG-mur7-uJbXmTZvJACtDjrM"
MAINTENANCE_PASSWORD = "uptuptupt"
