```python
# modules/admin/contract_proiect_like/contract_proiect_like_config.py

CONTRACT_PROIECT_LIKE_TYPES = {
    "cep": {
        "entity_type": "cep",
        "category_label": "Contracte",
        "type_label": "CEP",
        "base_table": "base_contracte_cep",
        "is_contract_ctx": True,
        "uses_standard_financial": True,
        "uses_fdi_financial": False,
        "uses_standard_tehnic": True,
        "tabs": [
            ("Date de bază", "base_contracte_cep"),
            ("Date financiare", "com_date_financiare"),
            ("Echipă", "com_echipe_proiect"),
            ("Aspecte tehnice", "com_aspecte_tehnice"),
        ],
        "label_profile": "contract",
        "dropdown_profile": "contract",
    },

    "terti": {
        "entity_type": "terti",
        "category_label": "Contracte",
        "type_label": "TERTI",
        "base_table": "base_contracte_terti",
        "is_contract_ctx": True,
        "uses_standard_financial": True,
        "uses_fdi_financial": False,
        "uses_standard_tehnic": True,
        "tabs": [
            ("Date de bază", "base_contracte_terti"),
            ("Date financiare", "com_date_financiare"),
            ("Echipă", "com_echipe_proiect"),
            ("Aspecte tehnice", "com_aspecte_tehnice"),
        ],
        "label_profile": "contract",
        "dropdown_profile": "contract",
    },

    "speciale": {
        "entity_type": "speciale",
        "category_label": "Contracte",
        "type_label": "SPECIALE",
        "base_table": "base_contracte_speciale",
        "is_contract_ctx": True,
        "uses_standard_financial": True,
        "uses_fdi_financial": False,
        "uses_standard_tehnic": True,
        "tabs": [
            ("Date de bază", "base_contracte_speciale"),
            ("Date financiare", "com_date_financiare"),
            ("Echipă", "com_echipe_proiect"),
            ("Aspecte tehnice", "com_aspecte_tehnice"),
        ],
        "label_profile": "contract",
        "dropdown_profile": "contract",
    },

    "fdi": {
        "entity_type": "fdi",
        "category_label": "Proiecte",
        "type_label": "FDI",
        "base_table": "base_proiecte_fdi",
        "is_contract_ctx": False,
        "uses_standard_financial": False,
        "uses_fdi_financial": True,
        "uses_standard_tehnic": True,
        "tabs": [
            ("Date de bază", "base_proiecte_fdi"),
            ("Date financiare", "com_date_financiare"),
            ("Echipă", "com_echipe_proiect"),
            ("Aspecte tehnice", "com_aspecte_tehnice"),
        ],
        "label_profile": "fdi",
        "dropdown_profile": "fdi",
    },

    "internationale": {
        "entity_type": "internationale",
        "category_label": "Proiecte",
        "type_label": "INTERNATIONALE",
        "base_table": "base_proiecte_internationale",
        "is_contract_ctx": False,
        "uses_standard_financial": True,
        "uses_fdi_financial": False,
        "uses_standard_tehnic": True,
        "tabs": [
            ("Date de bază", "base_proiecte_internationale"),
            ("Date financiare", "com_date_financiare"),
            ("Echipă", "com_echipe_proiect"),
            ("Aspecte tehnice", "com_aspecte_tehnice"),
        ],
        "label_profile": "proiect",
        "dropdown_profile": "proiect",
    },

    "interreg": {
        "entity_type": "interreg",
        "category_label": "Proiecte",
        "type_label": "INTERREG",
        "base_table": "base_proiecte_interreg",
        "is_contract_ctx": False,
        "uses_standard_financial": True,
        "uses_fdi_financial": False,
        "uses_standard_tehnic": True,
        "tabs": [
            ("Date de bază", "base_proiecte_interreg"),
            ("Date financiare", "com_date_financiare"),
            ("Echipă", "com_echipe_proiect"),
            ("Aspecte tehnice", "com_aspecte_tehnice"),
        ],
        "label_profile": "proiect",
        "dropdown_profile": "proiect",
    },

    "noneu": {
        "entity_type": "noneu",
        "category_label": "Proiecte",
        "type_label": "NONEU",
        "base_table": "base_proiecte_noneu",
        "is_contract_ctx": False,
        "uses_standard_financial": True,
        "uses_fdi_financial": False,
        "uses_standard_tehnic": True,
        "tabs": [
            ("Date de bază", "base_proiecte_noneu"),
            ("Date financiare", "com_date_financiare"),
            ("Echipă", "com_echipe_proiect"),
            ("Aspecte tehnice", "com_aspecte_tehnice"),
        ],
        "label_profile": "proiect",
        "dropdown_profile": "proiect",
    },

    "see": {
        "entity_type": "see",
        "category_label": "Proiecte",
        "type_label": "SEE",
        "base_table": "base_proiecte_see",
        "is_contract_ctx": False,
        "uses_standard_financial": True,
        "uses_fdi_financial": False,
        "uses_standard_tehnic": True,
        "tabs": [
            ("Date de bază", "base_proiecte_see"),
            ("Date financiare", "com_date_financiare"),
            ("Echipă", "com_echipe_proiect"),
            ("Aspecte tehnice", "com_aspecte_tehnice"),
        ],
        "label_profile": "proiect",
        "dropdown_profile": "proiect",
    },
}
```
